Update meteo.yml

diff --git a/.github/workflows/meteo.yml b/.github/workflows/meteo.yml
--- a/.github/workflows/meteo.yml
+++ b/.github/workflows/meteo.yml
@@ -48,14 +48,20 @@ jobs:
 
     - name: Test de notre projet
       run: |
-        $response = Invoke-WebRequest -Uri "http://localhost:5001/submit" -Method POST -Body city='Atakpame' -Headers @{ "Authorization" = "Bearer fc9a84b33a13593aca9630e7b38830d1" }
-        Write-Output "Response: $($response)"
-        if ($response.StatusCode -eq 200) {
-            Write-Host "Test réussi"
-        } else {
-            Write-Host "Test échoué"
-        }
-      
+        Start-Process powershell -ArgumentList {
+              # Requête de test avec la ville "Paris"
+              $formData = @{
+                city = 'Paris'
+              }
+              $response = Invoke-WebRequest -Uri "http://localhost:5001/submit" -Method POST -Body $formData -Headers @{ "Authorization" = "Bearer ${{ secrets.API_KEY }}" }
+              if ($response.StatusCode -eq 200) {
+                  Write-Host "Weather functionality test passed"
+              } else {
+                  Write-Error "Weather functionality test failed"
+                  exit 1
+              }
+          }
+        
     - name: Stop server
       run: |
         Stop-Process -Name "python" -Force  # Assurez-vous que le nom du processus est correct
